version: '3'
services:
  scheduler:
    image: imvexxed/nadcs:scheduler
    build: Scheduler/
    ports:
      - 1337:1337

  worker:
    image: imvexxed/nadcs:worker
    build: Worker/
    depends_on:
      - scheduler
    deploy:
      replicas: 3
    environment:
      - SCHEDULER_IP=scheduler
      - SCHEDULER_PORT=1337

  